# Generated by Django 6.0.2 on 2026-02-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttackIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('SQLI', 'SQL Injection'), ('XSS', 'Cross-Site Scripting'), ('BRUTE', 'Brute Force')], max_length=10)),
                ('payload', models.TextField(help_text='The malicious string or script used')),
                ('attacker_ip', models.GenericIPAddressField(default='127.0.0.1')),
            ],
        ),
    ]
